### ISSUE TITLE
Documentation fails

### ISSUE THREAD

**Issue by a-berg** [criteo/fromconfig#23]
Hello, 15 days ago or so this project had some change to documentation (instead of having a large README) and now it gives a 404 error when you try to access the webpage.

What's the problem here?

**Comment by rom1504** [comment]
https://criteo.github.io/fromconfig/#/ do you get a 404 there ?

**Comment by a-berg** [comment]
Yep

**Comment by guillaumegenthial** [comment]
Hello @a-berg 
We moved the documentation to another URL https://fromconfig.github.io/#/ let me know if you run into any other issues!

**Comment by guillaumegenthial** [comment]
(the previous URL should redirect to the new URL automatically)
